RegisterCommand('v4', function(source, args)
    local playerPed = PlayerPedId()
    local playerPos = GetEntityCoords(playerPed)
    local outputString = ('vec4(%.3f, %.3f, %.3f, %.3f)'):format(playerPos.x, playerPos.y, playerPos.z, GetEntityHeading(playerPed))
    lib.setClipboard(outputString)
    lib.notify({title = 'Clipboard set!', description = 'Your current position was copied to your clipboard in vector4 format.', icon = 'fas fa-clipboard'})
end)

RegisterCommand('v3', function(source, args)
    local playerPos = GetEntityCoords(PlayerPedId())
    local outputString = ('vec3(%.3f, %.3f, %.3f)'):format(playerPos.x, playerPos.y, playerPos.z)
    lib.setClipboard(outputString)
    lib.notify({title = 'Clipboard set!', description = 'Your current position was copied to your clipboard in vector3 format.', icon = 'fas fa-clipboard'})
end)

RegisterCommand('v2', function(source, args)
    local playerPos = GetEntityCoords(PlayerPedId())
    local outputString = ('vec2(%.3f, %.3f)'):format(playerPos.x, playerPos.y)
    lib.setClipboard(outputString)
    lib.notify({title = 'Clipboard set!', description = 'Your current position was copied to your clipboard in vector2 format.', icon = 'fas fa-clipboard'})
end)