InternalShared = InternalShared or {}
InternalShared.Items = {}
InternalShared.Items_T1 = {
    ["legmooseantler"] = {
        label = "Legendary Moose Antlers",
        description = "Animal Part",
        weight = 0.5,
        image = "mooseantler.png",
    },
    ["legbisonhorn"] = {
        label = "Legendary Bison Horns",
        description = "Animal Part",
        weight = 0.5,
        image = "bisonhorn.png",
    },
    ["legramhorn"] = {
        label = "Legendary Ram Horns",
        description = "Animal Part",
        weight = 0.5,
        image = "ramhorn.png",
    },
    ["legelkantler"] = {
        label = "Legendary Elk Antlers",
        description = "Animal Part",
        weight = 0.5,
        image = "elkantler.png",
    },
    ["legendbuckantler"] = {
        label = "Legendary Buck Antlers",
        description = "Animal Part",
        weight = 0.5,
        image = "buckantler.png",
    },
    ["legmooses1"] = {
        label = "Legendary Snowflake Moose pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "mooses.png",
    },
    ["legmooses2"] = {
        label = "Legendary Knight Moose pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "mooses.png",
    },
    ["legmooses3"] = {
        label = "Legendary Rudy Moose pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "mooses.png",
    },
    ["legfoxs1"] = {
        label = "Legendary Ota Fox pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "foxskin.png",
    },
    ["legfoxs2"] = {
        label = "Legendary Marble Fox pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "foxskin.png",
    },
    ["legfoxs3"] = {
        label = "Legendary Cross Fox pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "foxskin.png",
    },
    ["legelks1"] = {
        label = "Legendary Katata Elk pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "elks.png",
    },
    ["legelks2"] = {
        label = "Legendary Ozula Elk pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "elks.png",
    },
    ["legelks3"] = {
        label = "Legendary Inahme Elk pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "elks.png",
    },
    ["legbisons1"] = {
        label = "Legendary Tatanka Bison pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bisons.png",
    },
    ["legbisons2"] = {
        label = "Legendary Winyan Bison pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bisons.png",
    },
    ["legbisons3"] = {
        label = "Legendary Payata Bison pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bisons.png",
    },
    ["legbucks1"] = {
        label = "Legendary Buck pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "buks.png",
    },
    ["legbucks2"] = {
        label = "Legendary Mudrunner Buck pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "buks.png",
    },
    ["legbucks3"] = {
        label = "Legendary Snow Buck pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "buks.png",
    },
    ["legbucks4"] = {
        label = "Legendary Shadow Buck pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "buks.png",
    },
    ["legrams1"] = {
        label = "Legendary Gabbro Horn Ram pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "rams.png",
    },
    ["legrams2"] = {
        label = "Legendary Chalk Horn Ram pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "rams.png",
    },
    ["legrams3"] = {
        label = "Legendary Rutile Horn Ram pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "rams.png",
    },
    ["legrams4"] = {
        label = "Legendary GreatHorn Ram pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "rams.png",
    },
    ["legbears1"] = {
        label = "Legendary Deadly Bear pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bbears.png",
    },
    ["legbears2"] = {
        label = "Legendary Owiza Bear pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bbears.png",
    },
    ["legbears3"] = {
        label = "Legendary Ridgeback Spirit Bear pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bbears.png",
    },
    ["legbears4"] = {
        label = "Legendary Golden Spirit Bear pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bbears.png",
    },
    ["legwolfs1"] = {
        label = "Legendary Emerald Wolf pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "wolfpelt.png",
    },
    ["legwolfs2"] = {
        label = "Legendary Onyx Wolf pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "wolfpelt.png",
    },
    ["legwolfs3"] = {
        label = "Legendary Moonstone Wolf pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "wolfpelt.png",
    },
    ["legpanthers1"] = {
        label = "Legendary Nightwalker Panther pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "pantherss.png",
    },
    ["legpanthers2"] = {
        label = "Legendary Ghost Panther pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "pantherss.png",
    },
    ["legpanthers3"] = {
        label = "Legendary Iwakta Panther pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "pantherss.png",
    },
    ["legcoyotes1"] = {
        label = "Legendary Red Streak Coyote pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "coyotes.png",
    },
    ["legcoyotes2"] = {
        label = "Legendary Midnight Paw Coyote pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "coyotes.png",
    },
    ["legcoyotes3"] = {
        label = "Legendary Milk Coyote pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "coyotes.png",
    },
    ["legcougars1"] = {
        label = "Legendary Iguga Cougar pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "cougars.png",
    },
    ["legcougars2"] = {
        label = "Legendary Maza Cougar pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "cougars.png",
    },
    ["legcougars3"] = {
        label = "Legendary Sapa Cougar pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "cougars.png",
    },
    ["legcougars4"] = {
        label = "Legendary Black Cougar pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "cougars.png",
    },
    ["legboars1"] = {
        label = "Legendary Cogi Boar pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "boars.png",
    },
    ["legboars2"] = {
        label = "Legendary Wakpa Boar pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "boars.png",
    },
    ["legboars3"] = {
        label = "Legendary Icahi Boar pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "boars.png",
    },
    ["legboars4"] = {
        label = "Legendary Wildhog pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "boars.png",
    },
    ["legbeavers1"] = {
        label = "Legendary Grey Beaver pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "beavers.png",
    },
    ["legbeavers2"] = {
        label = "Legendary White Beaver pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "beavers.png",
    },
    ["legbeavers3"] = {
        label = "Legendary Black Beaver pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "beavers.png",
    },
    ["legaligators1"] = {
        label = "Legendary Teca Alligator pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "aligators.png",
    },
    ["legaligators2"] = {
        label = "Legendary Sun Alligator pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "aligators.png",
    },
    ["legaligators3"] = {
        label = "Legendary Banded Alligator pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "aligators.png",
    },
    ["legelks"] = {
        label = "Legendary Elk pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "elks.png",
    },
    ["leggbears"] = {
        label = "Legendary Bear skin",
        description = "Animal Part",
        weight = 2.0,
        image = "bbears.png",
    },
    ["legmooses"] = {
        label = "Legendary Moose pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "mooses.png",
    },
    ["legwolfpelt"] = {
        label = "Legendary Wolf skin",
        description = "Animal Part",
        weight = 1.0,
        image = "wolfpelt.png",
    },
    ["legprongs"] = {
        label = "Legendary Pronghorn skin",
        description = "Animal Part",
        weight = 1.0,
        image = "prongs.png",
    },
    ["legcoyotes"] = {
        label = "Legendary Coyote skin",
        description = "Animal Part",
        weight = 1.0,
        image = "coyotes.png",
    },
    ["legcougars"] = {
        label = "Legendary Cougar skin",
        description = "Animal Part",
        weight = 1.0,
        image = "cougars.png",
    },
    ["legbucks"] = {
        label = "Legendary Buck skin",
        description = "Animal Part",
        weight = 1.0,
        image = "bucks.png",
    },
    ["legbeawers"] = {
        label = "Legendary Beaver pelt",
        description = "Animal Part",
        weight = 0.4,
        image = "beavers.png",
    },
    ["legrams"] = {
        label = "Legendary Ram pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "rams.png",
    },
    ["legfoxskin"] = {
        label = "Legendary Fox skin",
        description = "Animal Part",
        weight = 0.5,
        image = "foxskin.png",
    },
    ["legboars"] = {
        label = "Legendary Boar pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "boars.png",
    },
    ["legbisonstak"] = {
        label = "Legendary Takanta Bison pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bisons.png",
    },
    ["legbisons"] = {
        label = "Legendary Bison pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bisons.png",
    },
    ["legaligators"] = {
        label = "Legendary Alligator pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "aligators.png",
    },
    ["legendsnakes"] = {
        label = "Legendary Boa pelt",
        description = "Animal Part",
        weight = 0.2,
        image = "snakeskin.png",
    },
    ["chipmunk_c"] = {
        label = "Chipmunk",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_chipmunk.png",
    },
    ["bat_c"] = {
        label = "Bat",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_bat.png",
    },
    ["bluejay_c"] = {
        label = "Blue jay",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_bluejay.png",
    },
    ["cardinal_c"] = {
        label = "Cardinal bird",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_cardinal.png",
    },
    ["cedarwaxwing_c"] = {
        label = "Cedar waxwing",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_cedarwaxwing.png",
    },
    ["crawfish_c"] = {
        label = "Crawfish",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_crawfish.png",
    },
    ["crab_c"] = {
        label = "Crab",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_crab.png",
    },
    ["crow_c"] = {
        label = "Crow",
        description = "Small Animal",
        weight = 0.1,
        image = "animal_crow.png",
    },
    ["frogbull_c"] = {
        label = "Frogbull",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_frogbull.png",
    },
    ["frogbull2_c"] = {
        label = "Poisoned Frogbull",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_frogbull.png",
    },
    ["oriole_c"] = {
        label = "Oriole",
        description = "Small Animal",
        weight = 0.1,
        image = "animal_oriole_baltimore.png",
    },
    ["oriole2_c"] = {
        label = "Hooded Oriole",
        description = "Small Animal",
        weight = 0.1,
        image = "animal_oriole_hooded.png",
    },
    ["pigeon_c"] = {
        label = "Pigeon",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_pigeon.png",
    },
    ["rat_c"] = {
        label = "Rat",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_rat.png",
    },
    ["robin_c"] = {
        label = "Robin",
        description = "Small Animal",
        weight = 0.08,
        image = "animal_robin.png",
    },
    ["songbird_c"] = {
        label = "Songbird",
        description = "Small Animal",
        weight = 0.08,
        image = "animal_songbird.png",
    },
    ["songbird2_c"] = {
        label = "Scarlet songbird",
        description = "Small Animal",
        weight = 0.08,
        image = "animal_songbird.png",
    },
    ["sparrow0_c"] = {
        label = "Common Sparrow",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_sparrow_eurasian.png",
    },
    ["sparrow1_c"] = {
        label = "Sparrow",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_sparrow.png",
    },
    ["sparrow2_c"] = {
        label = "Golden Sparrow",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_sparrow_golden.png",
    },
    ["squirrel_grey_c"] = {
        label = "Gray Squirrel",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_squirrel.png",
    },
    ["squirrel_red_c"] = {
        label = "Red Squirrel",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_squirrel.png",
    },
    ["squirrel_black_c"] = {
        label = "Black Squirrel",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_squirrel.png",
    },
    ["toad_c"] = {
        label = "Toad",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_toad.png",
    },
    ["toadpoison_c"] = {
        label = "Poisoned Toad",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_toad.png",
    },
    ["toaddesert_c"] = {
        label = "Desert Toad",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_toad.png",
    },
    ["woodpeck01_c"] = {
        label = "Woodpecker",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_woodpeck01.png",
    },
    ["woodpeck02_c"] = {
        label = "Woodpecker 2",
        description = "Small Animal",
        weight = 0.05,
        image = "animal_woodpeck02.png",
    },
---ANIMAL PARTS AND MEATS
    ["wool"] = {
        label = "Wool",
        description = "Item",
        weight = 0.001,
        limit = 100,
        image = "wool.png",
    },
    ["armadillos"] = {
        label = "Armadillo pelt",
        description = "Animal Part",
        weight = 0.1,
        image = "armadillos.png",
    },
    ["armadilloc"] = {
        label = "Armadillo claws",
        description = "Animal Part",
        weight = 0.001,
        image = "aclaw.png",
    },
    ["bearc"] = {
        label = "Bear claws",
        description = "Animal Part",
        weight = 0.03,
        image = "bearc.png",
    },
    ["beart"] = {
        label = "Bear tooth",
        description = "Animal Part",
        weight = 0.02,
        image = "atooth.png",
    },
    ["bbears"] = {
        label = "Black Bear Pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bbears.png",
    },
    ["gbears"] = {
        label = "Grizzly Bear Pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bbears.png",
    },
    ["ramhorn"] = {
        label = "Ram Horn",
        description = "Animal Part",
        weight = 0.1,
        image = "ramhorn.png",
    },
    ["rams"] = {
        label = "Ram pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "rams.png",
    },
    ["boarmusk"] = {
        label = "Boar tusk",
        description = "Animal Part",
        weight = 0.1,
        image = "boartusk.png",
    },
    ["boars"] = {
        label = "Boar pelt",
        description = "Animal Part",
        weight = 0.5,
        image = "boars.png",
    },
    ["porkfat"] = {
        label = "Pig fat",
        description = "Animal Part",
        weight = 0.1,
        image = "animalfat.png",
    },
    ["buckantler"] = {
        label = "Buck Antlers",
        description = "Animal Part",
        weight = 0.5,
        image = "buckantler.png",
    },
    ["bucks"] = {
        label = "Buck skin",
        description = "Animal Part",
        weight = 1.0,
        image = "bucks.png",
    },
    ["bisonhorn"] = {
        label = "Bison horn",
        description = "Animal Part",
        weight = 0.1,
        image = "bisonhorn.png",
    },
    ["bisons"] = {
        label = "Bison pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bisons.png",
    },
    ["bullhorn"] = {
        label = "Bull horn",
        description = "Animal Part",
        weight = 0.1,
        image = "bullhorn.png",
    },
    ["bulls"] = {
        label = "Bull pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "bulls.png",
    },
    ["deerskin"] = {
        label = "Deerskin",
        description = "Animal Part",
        weight = 0.8,
        image = "deerskin.png",
    },
    ["deerheart"] = {
        label = "Deer heart",
        description = "Animal Part",
        weight = 0.05,
        image = "aheart.png",
    },
    ["duckfat"] = {
        label = "Duck fat",
        description = "Animal Part",
        weight = 0.01,
        image = "animalfat.png",
    },
    ["eaglef"] = {
        label = "Eagle feather",
        description = "Animal Part",
        weight = 0.001,
        limit = 200,
        image = "feathersm.png",
    },
    ["eaglet"] = {
        label = "Eagle claws",
        description = "Animal Part",
        weight = 0.005,
        image = "eagletalon.png",
    },
    ["quailf"] = {
        label = "Quail feather",
        description = "Animal Part",
        weight = 0.001,
        limit = 200,
        image = "feathersm.png",
    },
    ["quailb"] = {
        label = "Quail beak",
        description = "Animal Part",
        weight = 0.005,
        image = "beak.png",
    },
    ["egretf"] = {
        label = "Snowy Egret feather",
        description = "Animal Part",
        weight = 0.001,
        image = "egretf.png",
    },
    ["egretb"] = {
        label = "Snowy Egret beak",
        description = "Animal Part",
        weight = 0.007,
        image = "smallbeak.png",
    },
    ["elkantler"] = {
        label = "Elk antler",
        description = "Animal Part",
        weight = 1.0,
        image = "elkantler.png",
    },
    ["elks"] = {
        label = "Vapiti pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "elks.png",
    },
    ["wolfheart"] = {
        label = "Wolf heart",
        description = "Animal Part",
        weight = 0.1,
        image = "aheart.png",
    },
    ["wolfpelt"] = {
        label = "Wolf skin",
        description = "Animal Part",
        weight = 1.0,
        image = "wolfpelt.png",
    },
    ["wolftooth"] = {
        label = "Wolf tooth",
        description = "Animal Part",
        weight = 0.01,
        image = "atooth.png",
    },
    ["condorf"] = {
        label = "Condor feather",
        description = "Animal Part",
        weight = 0.001,
        image = "featherlg.png",
    },
    ["condorb"] = {
        label = "Condor beak",
        description = "Animal Part",
        weight = 0.005,
        image = "beak.png",
    },
    ["kcondorf"] = {
        label = "Condor feather",
        description = "Animal Part",
        weight = 0.001,
        image = "featherlg.png",
    },
    ["kcondorb"] = {
        label = "Condor beak",
        description = "Animal Part",
        weight = 0.005,
        image = "smallbeak.png",
    },
    ["turtleshell"] = {
        label = "Turtle shell",
        description = "Animal Part",
        weight = 1.0,
        image = "turtleshell.png",
    },
    ["turtlet"] =
    {
        label = "Turtle tooth",
        description = "Animal Part",
        weight = 0.002,
        image = "atooth.png",
    },
    ["turkeyf"] =
    {
        label = "Turkey feather",
        description = "Animal Part",
        weight = 0.001,
        image = "feathersm.png",
    },
    ["turkeyb"] =
    {
        label = "Turkey beak",
        description = "Animal Part",
        weight = 0.005,
        image = "beak.png",
    },
    ["wsnakeskin"] =
    {
        label = "Watersnake pelt",
        description = "Animal Part",
        weight = 0.2,
        image = "snakeskin.png",
    },
    ["boaskin"] = {
        label = "Boa Snake pelt",
        description = "Animal Part",
        weight = 0.2,
        image = "snakeskin.png",
    },
    ["asnakes"] = {
        label = "Copperhead Snake pelt",
        description = "Animal Part",
        weight = 0.2,
        image = "snakeskin.png",
    },
    ["fsnakes"] = {
        label = "Blacktail rattlesnake pelt",
        description = "Animal Part",
        weight = 0.2,
        image = "snakeskin.png",
    },
    ["wsnakes"] = {
        label = "Western rattlesnake pelt",
        description = "Animal Part",
        weight = 0.2,
        image = "snakeskin.png",
    },
    ["snaket"] = {
        label = "Snake tooth",
        description = "Animal Part",
        weight = 0.001,
        image = "atooth.png",
    },
    ["badgers"] = {
        label = "Badger skin",
        description = "Animal Part",
        weight = 0.2,
        image = "badgers.png",
    },
    ["scentg"] = {
        label = "Scent Gland",
        description = "Animal Part",
        weight = 0.001,
        image = "scentg.png",
    },
    ["sheephead"] = {
        label = "Sheep head",
        description = "Animal Part",
        weight = 0.5,
        image = "sheephead.png",
    },
    ["seagullf"] = {
        label = "Seagull feather",
        description = "Animal Part",
        weight = 0.001,
        image = "feathersm.png",
    },
    ["seagullb"] = {
        label = "Seagull beak",
        description = "Animal Part",
        weight = 0.05,
        image = "smallbeak.png",
    },
    ["rspoonf"] = {
        label = "Roseta Spoonbill feather",
        description = "Animal Part",
        weight = 0.001,
        image = "plume.png",
    },
    ["rspoonb"] = {
        label = "Roseta Spoonbill beak",
        description = "Animal Part",
        weight = 0.1,
        image = "beak.png",
    },
    ["cockf"] = {
        label = "Rooster feather",
        description = "Animal Part",
        weight = 0.001,
        image = "feathersm.png",
    },
    ["cockc"] = {
        label = "Rooster claws",
        description = "Animal Part",
        weight = 0.002,
        image = "aclaw.png",
    },
    ["boobyf"] = {
        label = "Red-footed booby feather",
        description = "Animal Part",
        weight = 0.001,
        image = "boobyft.png",
    },
    ["boobyf"] = {
        label = "Red-footed booby beak",
        description = "Animal Part",
        weight = 0.01,
        image = "smallbeak.png",
    },
    ["ravenc"] = {
        label = "Raven claws",
        description = "Animal Part",
        weight = 0.001,
        image = "ravenc.png",
    },
    ["ravenf"] = {
        label = "Raven feather",
        description = "Animal Part",
        weight = 0.001,
        image = "ravenf.png",
    },
    ["raccoons"] = {
        label = "Raccoon skin",
        description = "Animal Part",
        weight = 0.2,
        image = "raccoons.png",
    },
    ["raccoont"] = {
        label = "Raccoon tooth",
        description = "Animal Part",
        weight = 0.001,
        image = "atooth.png",
    },
    ["rabbits"] = {
        label = "Rabbitskin",
        description = "Animal Part",
        weight = 0.2,
        image = "rabbits.png",
    },
    ["rabbitpaw"] = {
        label = "Rabbitfoot",
        description = "Animal Part",
        weight = 0.05,
        image = "rabbitpaw.png",
    },
    ["prairif"] = {
        label = "Prairi chicken feather",
        description = "Animal Part",
        weight = 0.001,
        image = "feathersm.png",
    },
    ["prairib"] = {
        label = "Prairi chicken beak",
        description = "Animal Part",
        weight = 0.01,
        image = "smallbeak.png",
    },
    ["prongs"] = {
        label = "Pronghorn skin",
        description = "Animal Part",
        weight = 1.0,
        image = "prongs.png",
    },
    ["pronghornh"] = {
        label = "Pronghorn horn",
        description = "Animal Part",
        weight = 0.1,
        image = "pronghornh.png",
    },
    ["boaskin"] = {
        label = "Boa Snakepelt",
        description = "Animal Part",
        weight = 0.1,
        image = "snakeskin.png",
    },
    ["foxskin"] = {
        label = "Foxskin",
        description = "Animal Part",
        weight = 0.5,
        image = "foxskin.png",
    },
    ["foxt"] = {
        label = "Fox tooth",
        description = "Animal Part",
        weight = 0.007,
        image = "atooth.png",
    },
    ["opossums"] = {
        label = "Opossum skin",
        description = "Animal Part",
        weight = 0.2,
        image = "opossums.png",
    },
    ["opossumc"] = {
        label = "Opossum claws",
        description = "Animal Part",
        weight = 0.005,
        image = "bobcat_claw.png",
    },
    ["pigs"] = {
        label = "Pig pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "pigs.png",
    },
    ["peasantf"] = {
        label = "Peasant feather",
        description = "Animal Part",
        weight = 0.001,
        image = "feathersm.png",
    },
    ["peasantb"] = {
        label = "Peasant beak",
        description = "Animal Part",
        weight = 0.01,
        image = "beak.png",
    },
    ["pelicanf"] = {
        label = "Pelican feather",
        description = "Animal Part",
        weight = 0.001,
        image = "pelicanf.png",
    },
    ["pelicanb"] = {
        label = "Pelican beak",
        description = "Animal Part",
        weight = 0.05,
        image = "smallbeak.png",
    },
    ["bparrotf"] = {
        label = "Parrot feather",
        description = "Animal Part",
        weight = 0.001,
        image = "parrotf.png",
    },
    ["bparrotb"] = {
        label = "Parrot beak",
        description = "Animal Part",
        weight = 0.01,
        image = "beak.png",
    },
    ["condorf"] = {
        label = "Condor feather",
        description = "Animal Part",
        weight = 0.001,
        image = "hawkf.png",
    },
    ["chickenf"] = {
        label = "Chicken feather",
        description = "Animal Part",
        weight = 0.001,
        image = "feathersm.png",
    },
    ["chickenheart"] = {
        label = "Chicken heart",
        description = "Animal Part",
        weight = 0.05,
        image = "aheart.png",
    },
    ["bbirdf"] = {
        label = "Cormorant feather",
        description = "Animal Part",
        weight = 0.001,
        image = "cormorantfeather.png",
    },
    ["bbirdb"] = {
        label = "Cormorant beak",
        description = "Animal Part",
        weight = 0.01,
        image = "smallbeak.png",
    },
    ["daruf"] = {
        label = "Crane feather",
        description = "Animal Part",
        weight = 0.001,
        image = "pelicanf.png",
    },
    ["darub"] = {
        label = "Crane beak",
        description = "Animal Part",
        weight = 0.1,
        image = "smallbeak.png",
    },
    ["goosef"] = {
        label = "Goose feather",
        description = "Animal Part",
        weight = 0.001,
        image = "featherlg.png",
    },
    ["gooseb"] = {
        label = "Goose beak",
        description = "Animal Part",
        weight = 0.03,
        image = "smallbeak.png",
    },
    ["kbirdf"] = {
        label = "Great Blue Heron feather",
        description = "Animal Part",
        weight = 0.001,
        image = "cranef.png",
    },
    ["kbirdb"] = {
        label = "Great Blue Heron beak",
        description = "Animal Part",
        weight = 0.05,
        image = "smallbeak.png",
    },
    ["hawkf"] = {
        label = "Hawk feather",
        description = "Animal Part",
        weight = 0.001,
        image = "hawkf.png",
    },
    ["hawkt"] = {
        label = "Hawk claws",
        description = "Animal Part",
        weight = 0.003,
        image = "eagletalon.png",
    },
    ["loonf"] = {
        label = "Common loon feather",
        description = "Animal Part",
        weight = 0.001,
        image = "egretf.png",
    },
    ["loonb"] = {
        label = "Common loon beak",
        description = "Animal Part",
        weight = 0.02,
        image = "smallbeak.png",
    },
    ["owlf"] = {
        label = "Owl feather",
        description = "Animal Part",
        weight = 0.001,
        image = "owlf.png",
    },
    ["owlt"] = {
        label = "Owl claws",
        description = "Animal Part",
        weight = 0.005,
        image = "eagletalon.png",
    },
    ["beawers"] = {
        label = "Beaver pelt",
        description = "Animal Part",
        weight = 0.4,
        image = "beavers.png",
    },
    ["beavertail"] = {
        label = "Beaver tail",
        description = "Animal Part",
        weight = 0.2,
        image = "beaver_tail.png",
    },
    ["aligatorto"] = {
        label = "Alligator tooth",
        description = "Animal Part",
        weight = 0.005,
        image = "atooth.png",
    },
    ["aligators"] = {
        label = "Alligator pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "aligators.png",
    },
    ["oxhorn"] = {
        label = "Angus Bull horn",
        description = "Animal Part",
        weight = 0.2,
        image = "oxhorn.png",
    },
    ["oxs"] = {
        label = "Angus Bull pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "oxs.png",
    },
    ["muskrats"] = {
        label = "Muskrat skin",
        description = "Animal Part",
        weight = 0.2,
        image = "muskrats.png",
    },
    ["mooseantler"] = {
        label = "Moose Antlers",
        description = "Animal Part",
        weight = 1.0,
        image = "mooseantler.png",
    },
    ["mooses"] = {
        label = "Moose pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "mooses.png",
    },
    ["pecaris"] = {
        label = "Peccary pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "javelinas.png",
    },
    ["dleguans"] = {
        label = "Desert Iguana pelt",
        description = "Animal Part",
        weight = 0.1,
        image = "iguanas.png",
    },
    ["gleguans"] = {
        label = "Green Iguana pelt",
        description = "Animal Part",
        weight = 0.1,
        image = "iguanas.png",
    },
    ["lizards"] = {
        label = "Lizard pelt",
        description = "Animal Part",
        weight = 0.1,
        image = "iguanas.png",
    },
    ["lizardl"] = {
        label = "Lizard foot",
        description = "Animal Part",
        weight = 0.02,
        image = "lizardleg.png",
    },
    ["goats"] = {
        label = "Goat pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "goats.png",
    },
    ["goathead"] = {
        label = "Goat head",
        description = "Animal Part",
        weight = 0.5,
        image = "goathead.png",
    },
    ["cougars"] = {
        label = "Cougar Pelt",
        description = "Animal Part",
        weight = 1.0,
        image = "cougars.png",
    },
    ["cougarf"] = {
        label = "Cougar tooth",
        description = "Animal Part",
        weight = 0.01,
        image = "fang.png",
    },
    ["coyotes"] = {
        label = "Coyote skin",
        description = "Animal Part",
        weight = 1.0,
        image = "coyotes.png",
    },
    ["coyotef"] = {
        label = "Coyote tooth",
        description = "Animal Part",
        weight = 0.01,
        image = "smallfang.png",
    },
    ["cows"] = {
        label = "Cow pelt",
        description = "Animal Part",
        weight = 2.0,
        image = "cows.png",
    },
    ["cowh"] = {
        label = "Cow horn",
        description = "Animal Part",
        weight = 0.1,
        image = "ahorn.png",
    },
    ["panthers"] = {
        label = "Panther skin",
        description = "Animal Part",
        weight = 1.0,
        image = "panthers.png",
    },
    ["panthere"] = {
        label = "Panther eyes",
        description = "Animal Part",
        weight = 0.001,
        image = "panthere.png",
    },

    ["mutton"] = {
        label = "Mutton Meat",
        description = "Raw meat",
        weight = 0.1,
        image = "mutton.png",
    },
    ["biggame"] = {
        label = "Big Game Meat",
        description = "Raw meat",
        weight = 0.1,
        image = "biggame.png",
    },
    ["venison"] = {
        label = "Venison",
        description = "Raw meat",
        weight = 0.1,
        image = "venison.png",
    },
    ["beef"] = {
        label = "Beef",
        description = "Raw meat",
        weight = 0.1,
        image = "beef.png",
    },
    ["aligatormeat"] = {
        label = "Alligator Meat",
        description = "Raw meat",
        weight = 0.1,
        image = "biggame.png",
    },
    ["bird"] = {
        label = "Bird Meat",
        description = "Raw meat",
        weight = 0.1,
        image = "bird.png",
    },
    ["game"] = {
        label = "Game Meat",
        description = "Raw meat",
        weight = 0.1,
        image = "game.png",
    },
    ["pork"] = {
        label = "Pork",
        description = "Raw meat",
        weight = 0.1,
        image = "pork.png",
    },
    ["fishmeat"] = {
        label = "Raw Fish Meat",
        description = "Raw meat",
        weight = 0.1,
        image = "fishmeat.png",
    },
    ["herptile"] = {
        label = "Herptile meat",
        description = "Raw meat",
        weight = 0.1,
        image = "herptile.png",
    },
    ["stringy"] = {
        label = "Stringy meat",
        description = "Raw meat",
        weight = 0.1,
        image = "stringy.png",
    },
    ["lambchop"] = {
        label = "Lambchop",
        description = "Raw meat",
        weight = 0.1,
        image = "LambChop.png",
    },

	["a_c_fishbluegil_01_ms"] = {
        label = "Bluegill",
        description = "The bluegill is a species of freshwater fish",
        weight = 0.1,
        image = "a_c_fishbluegil_01_ms.png",
    },
	["a_c_fishbluegil_01_sm"] = {
        label = "Small Bluegill",
        description = "The bluegill is a species of freshwater fish",
        weight = 0.1,
        image = "a_c_fishbluegil_01_sm.png",
    },
	["a_c_fishbullheadcat_01_ms"] = {
        label = "Bullhead Catfish",
        description = "Ameiurus is a genus of catfishes in the family Ictaluridae.",
        weight = 0.1,
        image = "a_c_fishbullheadcat_01_ms.png",
    },
	["a_c_fishbullheadcat_01_sm"] = {
        label = "Small Bullhead Catfish",
        description = "Ameiurus is a genus of catfishes in the family Ictaluridae.",
        weight = 0.1,
        image = "a_c_fishbullheadcat_01_sm.png",
    },
	["a_c_fishchainpickerel_01_ms"] = {
        label = "Chain pickerel",
        description = "The chain pickerel is a species of freshwater fish in the pike family of order Esociformes.",
        weight = 0.1,
        image = "a_c_fishchainpickerel_01_ms.png",
    },
	["a_c_fishchainpickerel_01_sm"] = {
        label = "Small Chain pickerel",
        description = "The chain pickerel is a species of freshwater fish in the pike family of order Esociformes.",
        weight = 0.1,
        image = "a_c_fishchainpickerel_01_sm.png",
    },
	["a_c_fishchannelcatfish_01_lg"] = {
        label = "Lengendary Catfish",
        description = "The channel catfish is North America's most numerous catfish species.",
        weight = 0.1,
        image = "a_c_fishchannelcatfish_01_lg.png",
    },
	["a_c_fishchannelcatfish_01_xl"] = {
        label = "Catfish",
        description = "The channel catfish is North America's most numerous catfish species.",
        weight = 0.1,
        image = "a_c_fishchannelcatfish_01_xl.png",
    },
	["a_c_fishlakesturgeon_01_lg"] = {
        label = "Legendary Lake Sturgeon",
        description = "The lake sturgeon, also known as the rock sturgeon, is a North American temperate freshwater fish",
        weight = 0.1,
        image = "a_c_fishlakesturgeon_01_lg.png",
    },
	["a_c_fishlargemouthbass_01_lg"] = {
        label = "Largemouth bass",
        description = "The largemouth bass is a carnivorous freshwater gamefish in the Centrarchidae family",
        weight = 0.1,
        image = "a_c_fishlargemouthbass_01_lg.png",
    },
	["a_c_fishlargemouthbass_01_ms"] = {
        label = "Small Largemouth Bass",
        description = "The largemouth bass is a carnivorous freshwater gamefish in the Centrarchidae family",
        weight = 0.1,
        image = "a_c_fishlargemouthbass_01_ms.png",
    },
	["a_c_fishlongnosegar_01_lg"] = {
        label = "Legendary Longnose Gar",
        description = "The longnose gar, also known as longnose garpike or billy gar,",
        weight = 0.1,
        image = "a_c_fishlongnosegar_01_lg.png",
    },
	["a_c_fishmuskie_01_lg"] = {
        label = "Legendary Muskie",
        description = "The muskellunge, often shortened to muskie, musky or lunge,",
        weight = 0.1,
        image = "a_c_fishmuskie_01_lg.png",
    },
	["a_c_fishperch_01_ms"] = {
        label = "Perch",
        description = "Perch is a common name for fish of the genus Perca,",
        weight = 0.1,
        image = "a_c_fishperch_01_ms.png",
    },
	["a_c_fishperch_01_sm"] = {
        label = "Small Perch",
        description = "Perch is a common name for fish of the genus Perca,",
        weight = 0.1,
        image = "a_c_fishperch_01_sm.png",
    },
	["a_c_fishrainbowtrout_01_lg"] = {
        label = "Legendary Rainbow Trout",
        description = "The rainbow trout is a trout and species of salmonid native to cold-water tributaries of the Pacific Ocean",
        weight = 0.1,
        image = "a_c_fishrainbowtrout_01_lg.png",
    },
	["a_c_fishrainbowtrout_01_ms"] = {
        label = "Rainbow Trout",
        description = "The rainbow trout is a trout and species of salmonid native to cold-water tributaries of the Pacific Ocean",
        weight = 0.1,
        image = "a_c_fishrainbowtrout_01_ms.png",
    },
	["a_c_fishredfinpickerel_01_ms"] = {
        label = "Redfin Pickerel",
        description = "The redfin pickerel is a subspecies of freshwater fish belonging to the pike family",
        weight = 0.1,
        image = "a_c_fishredfinpickerel_01_ms.png",
    },
	["a_c_fishredfinpickerel_01_sm"] = {
        label = "Small Redfin Pickerel",
        description = "The redfin pickerel is a subspecies of freshwater fish belonging to the pike family",
        weight = 0.1,
        image = "a_c_fishredfinpickerel_01_sm.png",
    },
	["a_c_fishrockbass_01_ms"] = {
        label = "Rock bass",
        description = "The rock bass, also known as the rock perch, goggle-eye, red eye",
        weight = 0.1,
        image = "a_c_fishrockbass_01_ms.png",
    },
	["a_c_fishrockbass_01_sm"] = {
        label = "Small Rock Bass",
        description = "The rock bass, also known as the rock perch, goggle-eye, red eye",
        weight = 0.1,
        image = "a_c_fishrockbass_01_sm.png",
    },
	["a_c_fishsalmonsockeye_01_lg"] = {
        label = "Legendary Sockeye Salmon",
        description = "The sockeye salmon, also called red salmon, kokanee salmon,",
        weight = 0.1,
        image = "a_c_fishsalmonsockeye_01_lg.png",
    },
	["a_c_fishsalmonsockeye_01_ml"] = {
        label = "Sockeye salmon",
        description = "The sockeye salmon, also called red salmon, kokanee salmon,",
        weight = 0.1,
        image = "a_c_fishsalmonsockeye_01_ml.png",
    },
	["a_c_fishsalmonsockeye_01_ms"] = {
        label = "Small Sockeye Salmon",
        description = "The sockeye salmon, also called red salmon, kokanee salmon,",
        weight = 0.1,
        image = "a_c_fishsalmonsockeye_01_ms.png",
    },
	["a_c_fishsmallmouthbass_01_lg"] = {
        label = "Smallmouth bass",
        description = "The smallmouth bass is a species of freshwater fish in the sunfish family",
        weight = 0.1,
        image = "a_c_fishsmallmouthbass_01_lg.png",
    },
	["a_c_fishsmallmouthbass_01_ms"] = {
        label = "Small Smallmouth Bass",
        description = "The smallmouth bass is a species of freshwater fish in the sunfish family",
        weight = 0.1,
        image = "a_c_fishsmallmouthbass_01_ms.png",
    },
    ["a_c_fishnorthernpike_01_lg"] = {
        label = "Legendary Northern Pike",
        description = "The northern pike is a species of carnivorous fish of the genus Esox.",
        weight = 0.1,
        image = "a_c_fishnorthernpike_01_lg.png",
    },

    ["parakeet_c"] ={ label = "Parakeet Carcass", description = "Animal Part", weight = 0.1,    image = "animal_parakeet.png", },
    ["bluejay_c2"] ={ label = "Bluejay (2) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_bluejay.png", },
    ["cardinal_c2"] ={ label = "Cardinal (2) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_cardinal.png", },
    ["cardinal_c3"] ={ label = "Cardinal (3) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_cardinal.png", },
    ["cedarwaxwing_c2"] ={ label = "Cedar Waxwing (2) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_cedarwaxwing.png", },
    ["cedarwaxwing_c3"] ={ label = "Cedar Waxwing (3) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_cedarwaxwing.png", },
    ["armadillo_c"] ={ label = "Armadillo Carcass", description = "Animal Part", weight = 0.3,    image = "animal_armadillo.png", },
    ["rattlesnake_c"] ={ label = "Black-Tailed Rattlesnake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["rattlesnake_c2"] ={ label = "Black-Tailed Rattlesnake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["ferdelance_c"] ={ label = "Fer-de-lance snake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["copperhead_c"] ={ label = "Souther Copperhead snake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["copperhead_c2"] ={ label = "Northern Copperhead snake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["boa_c"] ={ label = "Red-tailed Boa Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["boa_c2"] ={ label = "Sunglow Boa Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["boa_c3"] ={ label = "Rainbow Boa Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["watersnake_c"] ={ label = "Midland Water snake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["watersnake_c2"] ={ label = "Cottonmouth Water snake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["watersnake_c3"] ={ label = "Northern Water snake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["rattlesnake_c3"] ={ label = "Diamondback Rattlesnake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["rattlesnake_c4"] ={ label = "Diamondback Rattlesnake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["rattlesnake_c5"] ={ label = "Timber Rattlesnake Carcass", description = "Animal Part", weight = 0.2,    image = "animal_snake.png", },
    ["muskrat_c"] ={ label = "Muskrat Carcass", description = "Animal Part", weight = 0.2,    image = "animal_muskrat.png", },
    ["muskrat_c2"] ={ label = "Muskrat Carcass", description = "Animal Part", weight = 0.2,    image = "animal_muskrat.png", },
    ["rat_c2"] ={ label = "Rat (Mangy) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_rat.png", },
    ["rat_c3"] ={ label = "Rat (Brown) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_rat.png", },
    ["rat_c4"] ={ label = "Rat (Black) Carcass", description = "Animal Part", weight = 0.1,    image = "animal_rat.png", },
    ["gila_c"] ={ label = "Gila Monster Carcass", description = "Animal Part", weight = 0.1,    image = "carcass.png", },
    ["iguana2_c"] ={ label = "Desert Iguana Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["iguana_c"] ={ label = "Green Iguana Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["skunk_c"] ={ label = "Skunk Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["skunk2_c"] ={ label = "Skunk (2) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["skunk3_c"] ={ label = "Skunk (3) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["raccoon_c"] ={ label = "Raccoon Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["raccoon2_c"] ={ label = "Raccoon (2) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["raccoon3_c"] ={ label = "Raccoon (3) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["raccoon4_c"] ={ label = "Raccoon (4) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["rabbit_c"] ={ label = "Rabbit Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["rabbit2_c"] ={ label = "Rabbit (2) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["rabbit3_c"] ={ label = "Rabbit (3) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["rabbit4_c"] ={ label = "Rabbit (4) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["opossum_c"] ={ label = "Opossum Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["opossum2_c"] ={ label = "Opossum (2) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["opossum3_c"] ={ label = "Opossum (3) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["badger_c"] ={ label = "Badger Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["badger2_c"] ={ label = "Badger (2) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
    ["badger3_c"] ={ label = "Badger (3) Carcass", description = "Animal Part", weight = 0.4,    image = "carcass.png", },
}
for k,v in pairs(InternalShared.Items_T1) do
    InternalShared.Items[k] = v
    InternalShared.Items[k].name = k
    InternalShared.Items[k].weight = v.weight * 1000
end -- haha - Sinatra
GlobalState.Shared_Items = InternalShared.Items